name: CI

on:
  push:
    branches:
      - main

jobs:
  integration:
    name: Continuous integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - node: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node ${{ matrix.versions.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.versions.node }}
          cache: pnpm
      - name: Install node dependencies
        run: pnpm install
      - name: Check for formatting and linting errors
        run: pnpm biome ci .
      - name: Check for spelling errors
        run: pnpm check:spell
